#server.port=8081
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://bealuckydev:Und8gmvN1PPxhTcS@cluster0.zu4xk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true

spring:
  redis:
    host: localhost
    port: 6379

  #    uri: redis://default:xLCBEYBXQ7R1XB5PZmOYTYLNgXNusIWq@redis-17632.c264.ap-south-1-1.ec2.redns.redis-cloud.com:17632
  #    host: redis-17632.c264.ap-south-1-1.ec2.redns.redis-cloud.com
  #    port: 17632
  #    password: xLCBEYBXQ7R1XB5PZmOYTYLNgXNusIWq

  data:
    mongodb:
      uri: mongodb+srv://bealuckydev:Und8gmvN1PPxhTcS@cluster0.zu4xk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com    #server which handle email service
    port: 587     # for encrypted data
    username: bealucky.dev@gmail.com
    password: dbksbnbqjtlpixrl
    properties:
      mail:
        smtp:
          auth: true   #
          starttls:   #start transport layer security
            enable: true  #encryption

server:
  port: 8081
  servlet:
    context-path: /journal

weather:
  api:
    key: 17cb72e3fe119e19eed6f4b9d260e52d